run:
  timeout: 5m

output:
  formats:
    - format: colored-line-number

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
      text: dot-imports
    - path: (.+)\.go$
      text: "ST1000: at least one file in a package should have a package comment"
    - path: (.+)\.go$
      text: "should not use dot imports"
