name: "linuxptp-daemon: Close stale issues and PRs"
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    uses: redhat-cne/upstream-ptp-operator-monorepo/.github/workflows/_reusable-linuxptp-daemon-stale.yml@main