name: "linuxptp-daemon: Prow github actions"
on:
  issue_comment:
    types: [created]

jobs:
  prow:
    uses: redhat-cne/upstream-ptp-operator-monorepo/.github/workflows/_reusable-linuxptp-daemon-prow.yml@main
    secrets: inherit
